### ISSUE TITLE
Future support

### ISSUE THREAD

**Issue by astewart77** [vinsworldcom/nppChangedLines#11]
Now that n++ has a native changed line marker feature built in, do you plan to continue support for this plugin? Hopefully so, since the new feature is not ready for prime time, lacking hotkeys for next/prev search and having nothing like your panel. As is, it's not useful. I'm still using your ChangedLines in n++ 8.4.6 with no problems. Unless the native function reaches parity with your plugin, I hope you continue.

**Comment by vinsworldcom** [comment]
I will no longer be supporting this plugin as the feature is now in Notepad++ natively.  I can provide feature parity for most features with PythonScript extensions for the current native feature so no longer need this plugin.  The only feature I don't have is next/previous position which was an add-on to this plugin to emulate Location Navigate and arguably could have been it's own plugin; it is unrelated to change history.

Cheers.

**Comment by vinsworldcom** [comment]
@astewart77 checkout the latest artifact for your architecture:

https://github.com/vinsworldcom/nppChangedLines/actions/runs/3430832020

It no longer does plugin change tracking, but relies on the Scintilla Change History feature to do that but provides the margin width and color customizations as well as the panel.

Let me know if you encounter bugs.

Cheers.

**Comment by astewart77** [comment]
This is a pleasant surprise. I popped it in and a quick look is good. I'll push it some tomorrow.

I had made a Autohotkey startup script to provide next/prev hotkeys and hardcode (no gui)  some color settings to get by, but the killer is your panel. Glad to see it.

Alan

**Comment by vinsworldcom** [comment]
@astewart77 many changes - active development.  Keep checking back for [latest artifact](https://github.com/vinsworldcom/nppChangedLines/actions) to see if any bugs you encounter are fixed.

**Comment by astewart77** [comment]
indicators - YES ! Now I can get rid of my NppExecEvent script.

I have been styling mine in my startup script. It's also handy to have a hotkey to toggle indicators on-off for the current view. It can get a bit cluttered.

Three observations:

When I saw that your Go to Next Change worked correctly, I looked at the source code and saw that you had come across
[this SCI_MARKERNEXT bug](https://sourceforge.net/p/scintilla/bugs/2353/). I flailed with my script till I saw it. Same solution.

In the old ChangedLines plugin the default style for the markers was SCI_FULLMARK (26). Now it seems to be the Scintilla default of SCI_LEFTMARK (27).

After menu Clear Change History, the undo/redo toolbar buttons don't reset until you click focus back to the view.

**Comment by vinsworldcom** [comment]
@astewart77 maybe best to delete your ChangedLines.ini file and let the plugin recreate a new one.  There are many changes to this and lots of old items in the INI file that may lead to confusion.  I don't make any changes to the Scintilla / Notepad++ selected markers for Change History.  The undo/redo button has nothing to do with this plugin; however, when using the "Clear all change", one must [reset the undo history](https://www.scintilla.org/ScintillaDoc.html#SCI_GETCHANGEHISTORY) and I do so that may be causing that.

Cheers.
