### ISSUE TITLE
 Any Chance you can add Toolbar Icons For Previous/Next Location?

### ISSUE THREAD

**Issue by amiga-500** [vinsworldcom/nppChangedLines#12]
One nice thing about the old LocationNav plugin that is missing in your plugin is that it had a Previous Location and Next Location icons that could be added to the NPP toolbar.  Is it possible you can do the same for this too?  I use a plugin called Customize Toolbar and i always loved having a Prev/Next icons to quickly navigate while not needing to popup a nav panel (or keeping it up).

Also, in NPP dark mode (Preferences > Dark Mode > Enable Dark Mode) your panel's icons look a bit rough.  Making ur icons in rgba ICO instead of BMP would resolve that.

Nonetheless, thanks very much for keeping this plugin alive.

**Comment by vinsworldcom** [comment]
@amiga-500 The plugin doesn't really support Dark mode in that I don't pay attention to the Dark mode N++ notifications or do anything with them.  I don't use Dark mode so didn't see the point in learning the API for it.

Happy to take pull requests, even if you have RGBA ICO images that could work.

Cheers.

**Comment by vinsworldcom** [comment]
> I use a plugin called Customize Toolbar

You can use Customize Toolbar to create custom icons and link them to the plugin commands you want - "Previous" / "Next".  You can do this without this plugin creating toolbar icons.  Give that a try and let me know if that works.

Cheers.
