### ISSUE TITLE
Suggestion:  Add version info and "where to find"

### ISSUE THREAD

**Issue by sasumner** [vinsworldcom/nppChangedLines#5]
As I was attempting to point someone requesting "change markers" on the N++ issues list (here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8611 ) to this most excellent plugin, I realized that just by looking at the installed plugin via Notepad++'s Plugin menu, I couldn't find version number info, nor where the plugin is hosted using that mechanism.  It would be nice to have this data in the user interface.

As I'm sure you know, most plugins do this by having an _About..._ menu item.  A super example (not that it is needed to get the point across), is the _Better MultiSelection_ plugin's popup when its _About..._ menu item is invoked:

![image](https://user-images.githubusercontent.com/30118311/88544914-29de0580-cfe8-11ea-8035-11c9d7f23b3c.png)

**Comment by vinsworldcom** [comment]
It is super simple - I'll include it in the next version I'm working on now (locnav branch).

**Comment by vinsworldcom** [comment]
Fixed in [0.2.4.1](https://github.com/vinsworldcom/nppChangedLines/releases/tag/0.2.4.1)

**Comment by sasumner** [comment]
I like it:

![image](https://user-images.githubusercontent.com/30118311/96466964-6e98c780-11f8-11eb-855d-00c0cd272082.png)

Curious, why is the `Version` text is greyed out?

**Comment by vinsworldcom** [comment]
Aesthetics?  I tried normal and it looked like a config item to set rather
than an informational read-only label for the clickable link.

Cheers.
