### ISSUE TITLE
Localization of the "ChangedLines" plugin using the "nativeLang" plugin

### ISSUE THREAD

**Issue by andrecool-68** [vinsworldcom/nppChangedLines#7]
How can localize the "ChangedLines" plugin using the "nativeLang" plugin?

**Comment by vinsworldcom** [comment]
I'm not familiar with the nativeLang plugin.  Do you have a link for it?

You can always fork this plugin and convert the menu items / dialog boxes to your native language, compile and use.  This is not "really" my original code - most logic is taken from the original [LocationNavigate ](https://sourceforge.net/projects/locationnav/)plugin which didn't work on 64-bit and my trying to get it to work was failing.  Starting over was easier.

Cheers.

**Comment by andrecool-68** [comment]
@vinsworldcom These are plugin links and example language file:
https://sourceforge.net/projects/npp-plugins/files/NativeLang/
https://sourceforge.net/p/npp-plugins/discussion/759947/thread/7b6e2417/
For example, a plugin with a Russian localization file:
[NativeLang.zip](https://github.com/vinsworldcom/nppChangedLines/files/5283716/NativeLang.zip)

**Comment by vinsworldcom** [comment]
It looks ancient - from 2008 and no 64 bit version?

Looks like you only need a translation file according to your second link?  Can you create that and just put it in the appropriate location?

**Comment by andrecool-68** [comment]
@vinsworldcom 
I need to extract the strings for translation into this configuration file, I cannot figure out how to extract these strings for the original.
