### ISSUE TITLE
"Changed Lines Panel" Empty window on a real computer

### ISSUE THREAD

**Issue by andrecool-68** [vinsworldcom/nppChangedLines#8]
Virtual machine VirtualBox windows 7 x32

![1](https://user-images.githubusercontent.com/3471892/94292848-29210b80-ff66-11ea-8966-0fda31425f72.png)

Real computer windows 7 x64

![2](https://user-images.githubusercontent.com/3471892/94292849-2aeacf00-ff66-11ea-82f1-39c311c57569.png)

I've tested different versions on a real computer, but I still see this blank window.

**Comment by vinsworldcom** [comment]
Strange.  I see that's not the latest development version since I've removed the "Enabled" checkbox from the panel in that version.  I have Windows 7 x64 on my other computer an the panel shows fine for me.  Are you using the latest release version?

**Comment by andrecool-68** [comment]
@vinsworldcom These are the most recent versions of notepad ++ and your plugin, I tested on a real Win7x64 computer.

![x32](https://user-images.githubusercontent.com/3471892/96078261-7c79e000-0eba-11eb-83fb-8b6bec21c347.png)

![x64](https://user-images.githubusercontent.com/3471892/96078262-7dab0d00-0eba-11eb-8b1c-10eb5c67ef05.png)

**Comment by vinsworldcom** [comment]
Here's a long shot as I had a problem with displaying the panel on first creating it.

1. Open Notepad++
2. Plugins => Changed Lines => Changed Lines Panel
3. Plugins => Changed Lines => Changed Lines Panel
4. Plugins => Changed Lines => Changed Lines Panel

Assuming Notepad++ on open does not have Changed Lines panel visible, that should create the panel and maybe make it visible with the error you see.  Close the panel, Open it again after having created / initialized it so it should draw OK.

There is a fix for the "open on create" issue in the develop branch if you feel inclined to grab the latest [pre-release](https://github.com/vinsworldcom/nppChangedLines/releases/tag/0.2.4.1).

Cheers.
